import Footer from '@/components/website/layout/footer/footer';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Zway - website',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='flex flex-col items-center overflow-x-hidden'>
      <div className='min-h-screen w-screen'>{children}</div>
      <Footer bg='secondary' type='waitlist' border={false} />
    </div>
  );
}
