name: Deploy backend Railway

on:
  push:
    branches:
      - maing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if backend directory has changed
        id: check_changes
        run: |
          git diff --exit-code backend/ || echo "Changes detected in backend/ directory."

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Test build
        run: |
          cd backend
          go build cmd/main.go

      - name: Railway Deploy
        if: steps.check_changes.outcome == 'success'
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "Backend"
