name: Deploy Backend Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if backend directory has changed
        id: check_changes
        run: |
          # Check for changes in the backend directory
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^backend/'; then
            echo "Changes detected in the backend directory"
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "No changes detected in the backend directory"
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Set up Go
        if: env.changes == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Test build
        if: env.changes == 'true'
        run: |
          cd backend
          go build cmd/main.go

      - name: Railway Deploy
        if: env.changes == 'true'
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "Backend"
