name: Deploy Backend Railway

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Check for changes in backend directory
        id: changes
        run: |
          echo "Checking for changes in the backend directory..."
          if git diff --quiet HEAD^ HEAD -- backend/; then
            echo "No changes detected in the backend directory."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in the backend directory."
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Test build
        if: steps.changes.outputs.skip == 'false'
        run: |
          cd backend
          go build cmd/main.go

      - name: Railway Deploy
        if: steps.changes.outputs.skip == 'false'
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "Backend"
