name: Deploy Measurely SaaS to Railway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install pnpm
      run: |
        npm install -g pnpm

    - name: Install dependencies and build the app
      run: |
        cd frontend
        pnpm install
        pnpm build

    - name: Install Railway CLI
      run: |
        curl -fsSL https://github.com/railwayapp/railway/releases/download/v1.7.0/railway-linux-x64.tar.gz | tar -xz -C /usr/local/bin

    - name: Authenticate with Railway CLI
      run: |
        railway login --token ${{ secrets.RAILWAY_TOKEN }}

    - name: Deploy to Railway
      run: |
        railway up
