name: Deploy Content Railway

on:
  push:
    branches:
      - main
    paths:
      - "content/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Check for changes in content directory
        id: changes
        run: |
          echo "Checking for changes in the content directory..."
          if git diff --quiet HEAD^ HEAD -- content/; then
            echo "No changes detected in the content directory."
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in the content directory."
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        if: steps.changes.outputs.skip == 'false'
        run: |
          cd content
          pnpm install

      - name: Build Next.js app
        if: steps.changes.outputs.skip == 'false'
        run: |
          cd frontend
          pnpm run build

      - name: Railway Deploy
        if: steps.changes.outputs.skip == 'false'
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "Content"
