name: Deploy frontend Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if frontend directory has changed
        id: check_changes
        run: |
          git diff --exit-code frontend/ || echo "Changes detected in frontend/ directory."

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          cd frontend
          pnpm install

      - name: Build Next.js app
        run: |
          cd frontend
          pnpm run build

      - name: Railway Deploy
        if: steps.check_changes.outcome == 'success'
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "Frontend"
