import type { Metadata } from 'next';
import DashboardWrapper from './wrapper';

export const metadata: Metadata = {
  title: 'Zway - website',
  description: 'Generated by create next app',
};

export default function DashboardContentLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <DashboardWrapper>{children}</DashboardWrapper>;
}
